# GitGuardian Configuration
# Allowlist for test fixtures and benign secrets

version: 2

# Paths to exclude from scanning
paths:
  exclude:
    - "**/__tests__/**"
    - "**/test/**"
    - "**/tests/**"
    - "**/*.test.*"
    - "**/*.spec.*"
    - "**/fixtures/**"
    - "**/mocks/**"
    - "**/sample/**"
    - "**/examples/**"
    - "ci_audit/**"
    - "docs/examples/**"

# Specific matches to ignore (test fixtures and documentation)
ignored-matches:
  # JWT CLI usage documentation - not real secrets
  - name: jwt-cli-usage-docs
    match: "pnpm tsx scripts/ci/lib/jwt.ts decode --token"
  
  - name: jwt-cli-usage-verify
    match: "pnpm tsx scripts/ci/lib/jwt.ts verify --token"
    
  # Test JWT secrets (clearly marked as test/demo)
  - name: test-jwt-secret
    match: "test-jwt-secret"
  
  - name: demo-jwt-secret
    match: "demo-jwt-secret"
    
  - name: ci-test-jwt
    match: "test-secret-123"
    
  - name: example-auth-token
    match: "example-auth-token"
    
  # Test database URLs
  - name: test-database-url
    match: "postgresql://test:test@localhost"
    
  - name: sqlite-test-db
    match: "test_hotdog_diaries.db"

# Only scan for high-confidence secrets
verbose: false