# GitGuardian Configuration
# Allowlist for test fixtures and benign secrets

version: v1

# Paths to ignore completely  
paths-ignore:
  - "**/__tests__/**"
  - "**/test/**"
  - "**/tests/**"
  - "**/*.test.*"
  - "**/*.spec.*"
  - "**/fixtures/**"
  - "**/mocks/**"
  - "**/sample/**"
  - "**/examples/**"
  - "scripts/ci/**"
  - "ci_audit/**"

# Specific secrets to ignore (test fixtures only)
secrets-ignore:
  # Test JWT secrets (clearly marked as test/demo)
  - name: "Test JWT Secret"
    match: "test-jwt-secret"
  
  - name: "Demo JWT Secret"  
    match: "demo-jwt-secret"
    
  - name: "CI Test JWT"
    match: "test-secret-123"
    
  - name: "Example Auth Token"
    match: "example-auth-token"
    
  # Test database URLs
  - name: "Test Database URL"
    match: "postgresql://test:test@localhost"
    
  - name: "SQLite Test DB"
    match: "test_hotdog_diaries.db"
    
  # Secret scanning patterns (not actual secrets)
  - name: "JWT Pattern in Security Script"
    match: "eyJ[A-Za-z0-9_-]{100,}"

# File patterns for test secrets
file-ignore:
  - "*.env.example"
  - "*.env.test" 
  - ".env.ci"
  - "*.sample"
  - "package.json"
  - "package-lock.json"
  - "pnpm-lock.yaml"

# Only scan for high-confidence secrets
minimum-occurrences: 2
minimum-entropy: 3.5

# Specific detectors to disable for test files
detectors-ignore:
  - "generic_high_entropy_secret"  # Often false positives in test data
  - "generic_password"             # Test passwords are acceptable