name: Daily Ingestion Balance Report

on:
  schedule:
    # Run at 9 AM UTC daily (5 AM ET)
    - cron: '0 9 * * *'
  workflow_dispatch:
    inputs:
      format:
        description: 'Output format'
        required: false
        default: 'table'
        type: choice
        options:
          - table
          - json

jobs:
  ingestion-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - run: npm ci
      
      - name: Generate Ingestion Balance Report
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY_V2 != '' && secrets.SUPABASE_SERVICE_ROLE_KEY_V2 || secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: |
          if [ "${{ github.event.inputs.format }}" = "json" ]; then
            npx tsx scripts/ingestion-balance-report.ts --format=json
          else
            npx tsx scripts/ingestion-balance-report.ts
          fi
      
      - name: Check Alert Thresholds
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY_V2 != '' && secrets.SUPABASE_SERVICE_ROLE_KEY_V2 || secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: npx tsx scripts/ingestion-balance-report.ts --alert-thresholds
        continue-on-error: true
        id: alerts
      
      - name: Create Issue on Alerts
        if: steps.alerts.outcome == 'failure'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Ingestion Balance Alert - ' + new Date().toISOString().split('T')[0],
              body: 'Automated ingestion balance monitoring detected issues. Check the workflow logs for details.',
              labels: ['ingestion', 'alert', 'automated']
            })
