name: Post Breakfast Content

on:
  schedule:
    - cron: '0 7 * * *'  # 7:00 UTC = 2:00 AM ET (legacy schedule maintained)
  workflow_dispatch:

permissions:
  contents: read

jobs:
  post-breakfast:
    uses: ./.github/workflows/post-time-slot.yml
    with:
      slot_name: breakfast-legacy
      slot_time: "2:00 AM ET (Legacy Schedule)"
      target_url: 'https://hotdog-diaries.vercel.app'
      enable_diversity_guard: true
    secrets: inherit