name: Post Breakfast Content

on:
  schedule:
    - cron: '0 7 * * *'  # 7 AM UTC
  workflow_dispatch:

jobs:
  post-breakfast:
    runs-on: ubuntu-latest
    steps:
      - name: Post Breakfast Content
        run: |
          echo "🌅 Posting breakfast content..."
          curl -L -X POST "${{ secrets.SITE_URL }}/api/admin/posting/post-now" \
            -H "Authorization: Bearer ${{ secrets.AUTH_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"immediate": true}' \
            --fail --show-error --retry 2 --retry-delay 10
      
      - name: Verify Post Success
        if: success()
        run: |
          echo "✅ Breakfast content posted successfully"
          # Optional: Send success notification
      
      - name: Handle Failure
        if: failure()
        run: |
          echo "❌ Breakfast posting failed - alerting team"
          # Could integrate with Slack/Discord/email alerts here