# DEPRECATED: This workflow has been replaced by individual smart scanning workflows
# Individual workflows now use threshold-based scanning to optimize API usage
# - scan-lemmy.yml (smart threshold-based scanning)
# - scan-tumblr.yml (smart threshold-based scanning)
#
# Disabled to prevent bypassing smart scanning thresholds for underrepresented platforms

name: Scan Niche Platforms (DEPRECATED)

on:
  # schedule:
  #   - cron: '3 6,14,22 * * *'  # DISABLED - replaced by individual smart workflows
  workflow_dispatch:
    inputs:
      confirm_override:
        description: 'This workflow is deprecated. Use individual platform workflows instead.'
        required: true
        default: 'I understand this is deprecated'
        type: string

jobs:
  deprecated-notice:
    runs-on: ubuntu-latest
    steps:
      - name: Deprecated Workflow Notice
        run: |
          echo "🚨 DEPRECATED: This workflow has been replaced by individual smart workflows"
          echo ""
          echo "This batch workflow bypassed smart scanning thresholds for underrepresented platforms."
          echo "Niche platforms (Lemmy, Tumblr) have critically low content and need prioritized scanning."
          echo ""
          echo "✅ Use these individual workflows instead:"
          echo "   • scan-lemmy.yml (smart threshold-based with priority for underrepresented platforms)"
          echo "   • scan-tumblr.yml (smart threshold-based with priority for underrepresented platforms)"
          echo ""
          echo "💡 Smart workflows prioritize scanning underrepresented platforms while"
          echo "   skipping high-volume platforms when content surplus exists."
          echo ""
          
          CONFIRM="${{ github.event.inputs.confirm_override }}"
          if [ "$CONFIRM" != "I understand this is deprecated" ]; then
            echo "❌ This workflow requires confirmation to prevent accidental usage"
            exit 1
          fi
          
          echo "⚠️ Manual override confirmed - workflow functionality disabled for safety"