name: Scan Giphy for Content

on:
  schedule:
    - cron: '0 2,10,18 * * *'  # 3 times daily (2 AM, 10 AM, 6 PM UTC)
  workflow_dispatch:

jobs:
  scan-giphy:
    runs-on: ubuntu-latest
    steps:
      - name: Scan Giphy
        run: |
          echo "🎭 Scanning Giphy for hotdog GIFs..."
          
          curl -X POST "${{ secrets.SITE_URL }}/api/admin/giphy/scan" \
            -H "Authorization: Bearer ${{ secrets.AUTH_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"maxPosts": 15}' \
            --fail --show-error --retry 2 --retry-delay 5
          
          echo "✅ Giphy scan completed"
      
      - name: Handle Scan Failure
        if: failure()
        run: |
          echo "❌ Giphy scanning failed - will retry on next scheduled run"