# DEPRECATED: This workflow has been replaced by individual smart scanning workflows
# Individual workflows now use threshold-based scanning to optimize API usage
# - scan-giphy.yml (smart threshold-based scanning)
# - scan-bluesky.yml (smart threshold-based scanning)  
# - scan-imgur.yml (smart threshold-based scanning)
# - scan-pixabay.yml (smart threshold-based scanning)
#
# Disabled to prevent bypassing smart scanning thresholds

name: Scan Social Platforms (DEPRECATED)

on:
  # schedule:
  #   - cron: '0 1,9,17 * * *'  # DISABLED - replaced by individual smart workflows
  workflow_dispatch:
    inputs:
      confirm_override:
        description: 'This workflow is deprecated. Use individual platform workflows instead.'
        required: true
        default: 'I understand this is deprecated'
        type: string

jobs:
  deprecated-notice:
    runs-on: ubuntu-latest
    steps:
      - name: Deprecated Workflow Notice
        run: |
          echo "🚨 DEPRECATED: This workflow has been replaced by individual smart workflows"
          echo ""
          echo "This batch workflow bypassed smart scanning thresholds, causing unnecessary API usage."
          echo ""
          echo "✅ Use these individual workflows instead:"
          echo "   • scan-giphy.yml (smart threshold-based)"
          echo "   • scan-bluesky.yml (smart threshold-based)"  
          echo "   • scan-imgur.yml (smart threshold-based)"
          echo "   • scan-pixabay.yml (smart threshold-based)"
          echo ""
          echo "💡 Smart workflows automatically skip scanning when content surplus exists,"
          echo "   preserving API quotas for underrepresented platforms."
          echo ""
          
          CONFIRM="${{ github.event.inputs.confirm_override }}"
          if [ "$CONFIRM" != "I understand this is deprecated" ]; then
            echo "❌ This workflow requires confirmation to prevent accidental usage"
            exit 1
          fi
          
          echo "⚠️ Manual override confirmed - workflow functionality disabled for safety"